export default [
  {
    title: "Learning Ruby on Rails",
    subtitle: "My first backend experience",
    date: "July 15, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id pharetra felis. Quisque sit amet nisi pellentesque, consequat augue sed, tempor odio. Nunc finibus non velit faucibus eleifend. Donec id efficitur dolor, quis laoreet nunc. Suspendisse gravida tellus diam, ut placerat massa fermentum sed. Praesent efficitur ante sit amet ex aliquam tincidunt. Pellentesque dolor mi, porta ut felis vel, euismod consectetur nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras semper bibendum arcu, eget rhoncus nulla gravida a. Nunc sollicitudin neque at felis laoreet blandit. Duis elit nisl, congue ac felis nec, suscipit fermentum arcu. Pellentesque sagittis pretium quam, in tristique ipsum porttitor ac. Integer tristique velit sem, in fringilla augue interdum non. Fusce molestie sed tortor non egestas. Donec luctus enim eget ex pretium blandit. \n Phasellus porta placerat sapien, at fringilla urna consequat id. Maecenas vel lacus sit amet ipsum interdum porta. Morbi nec turpis ornare, auctor leo ut, malesuada ante. Maecenas ultrices eu purus et dictum. Pellentesque rhoncus tempus est, sed imperdiet risus accumsan id. Duis nec leo efficitur elit venenatis lacinia ut a tellus. Nam molestie, metus ac viverra facilisis, velit eros maximus libero, ut scelerisque eros nunc vitae nisi. Etiam consequat ornare fermentum. Cras id tempor nibh."
  },
  {
    title: "Learning Vue.js",
    subtitle: "My first frontend experience",
    date: "August 13, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id pharetra felis. Quisque sit amet nisi pellentesque, consequat augue sed, tempor odio. Nunc finibus non velit faucibus eleifend. Donec id efficitur dolor, quis laoreet nunc. Suspendisse gravida tellus diam, ut placerat massa fermentum sed. Praesent efficitur ante sit amet ex aliquam tincidunt. Pellentesque dolor mi, porta ut felis vel, euismod consectetur nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras semper bibendum arcu, eget rhoncus nulla gravida a. Nunc sollicitudin neque at felis laoreet blandit. Duis elit nisl, congue ac felis nec, suscipit fermentum arcu. Pellentesque sagittis pretium quam, in tristique ipsum porttitor ac. Integer tristique velit sem, in fringilla augue interdum non. Fusce molestie sed tortor non egestas. Donec luctus enim eget ex pretium blandit. \n Phasellus porta placerat sapien, at fringilla urna consequat id. Maecenas vel lacus sit amet ipsum interdum porta. Morbi nec turpis ornare, auctor leo ut, malesuada ante. Maecenas ultrices eu purus et dictum. Pellentesque rhoncus tempus est, sed imperdiet risus accumsan id. Duis nec leo efficitur elit venenatis lacinia ut a tellus. Nam molestie, metus ac viverra facilisis, velit eros maximus libero, ut scelerisque eros nunc vitae nisi. Etiam consequat ornare fermentum. Cras id tempor nibh."
  },
  {
    title: "Learning React.js",
    subtitle: "My first self-directed frontend learning experience",
    date: "December 4, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id pharetra felis. Quisque sit amet nisi pellentesque, consequat augue sed, tempor odio. Nunc finibus non velit faucibus eleifend. Donec id efficitur dolor, quis laoreet nunc. Suspendisse gravida tellus diam, ut placerat massa fermentum sed. Praesent efficitur ante sit amet ex aliquam tincidunt. Pellentesque dolor mi, porta ut felis vel, euismod consectetur nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras semper bibendum arcu, eget rhoncus nulla gravida a. Nunc sollicitudin neque at felis laoreet blandit. Duis elit nisl, congue ac felis nec, suscipit fermentum arcu. Pellentesque sagittis pretium quam, in tristique ipsum porttitor ac. Integer tristique velit sem, in fringilla augue interdum non. Fusce molestie sed tortor non egestas. Donec luctus enim eget ex pretium blandit. \n Phasellus porta placerat sapien, at fringilla urna consequat id. Maecenas vel lacus sit amet ipsum interdum porta. Morbi nec turpis ornare, auctor leo ut, malesuada ante. Maecenas ultrices eu purus et dictum. Pellentesque rhoncus tempus est, sed imperdiet risus accumsan id. Duis nec leo efficitur elit venenatis lacinia ut a tellus. Nam molestie, metus ac viverra facilisis, velit eros maximus libero, ut scelerisque eros nunc vitae nisi. Etiam consequat ornare fermentum. Cras id tempor nibh."
  }
]